joint_st_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

left_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_left

right_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_right